export type Section={h:string;p:string[];tip?:string};
export type Post={slug:string;title:string;excerpt:string;category:string;date:string;read:number;ratio:string;tone:string;body:Section[]};
export const SITE={name:"Build & Bloom Hub",tagline:"Learn. Build. Grow. Bloom.",url:process.env.NEXT_PUBLIC_SITE_URL||"https://example.com"};
export const categories=[["budgeting","Budgeting"],["saving","Saving"],["make-money-online","Make Money Online"],["side-hustles","Side Hustles"],["ai-tools","AI Tools"],["personal-finance","Personal Finance"],["freelancing","Freelancing"],["digital-skills","Digital Skills"],["lifestyle","Lifestyle"]].map(([slug,name])=>({slug,name}));
export const catSlug=(n:string)=>categories.find(c=>c.name===n)?.slug??"";
const P=(slug:string,title:string,category:string,date:string,read:number,ratio:string,tone:string,excerpt:string,body:Section[]):Post=>({slug,title,category,date,read,ratio,tone,excerpt,body});
export const posts:Post[]=[
P("how-to-create-a-simple-budget","How to Create a Simple Budget That Actually Works","Budgeting","2026-09-28",5,"aspect-[2/3]","bg-mist","A simple budget takes twenty minutes. Here is the three-bucket plan that shows women where every dollar goes.",[
{h:"Why your last budget fell apart",p:["Most people don't fail at a simple budget. The budget fails them. You list every bill on a Sunday and promise yourself $300 for groceries. By the 20th you've spent $450, the plan feels ruined, and you quit.","That's a design problem, not a character flaw. The numbers were hopeful, the plan had no wiggle room, and one overspend broke it. Here's a version built to survive real life."]},
{h:"Start with the money that actually lands",p:["Open your banking app and find your take-home pay. Not the salary on your contract. The amount that arrives after tax and deductions.","Say you take home $2,400 a month. That's your number. If your pay changes from month to month, use your lowest recent month, and treat anything extra as a bonus you assign later."],tip:"These examples use US dollars. Swap in your own currency. The percentages work the same anywhere."},
{h:"Look at what you really spend",p:["Pull up the last two months of bank or mobile money statements and scroll. It's uncomfortable. It's also where the real plan comes from.","You're not judging yourself. You're hunting for patterns. Expect a few usual suspects. A forgotten subscription. Small daily purchases that add up. Bank fees that quietly drain a little each month.","Write down the fixed costs first, the ones that never change, like rent, transport, phone and loan payments. Then estimate the ones that wobble, like food and fun, using what you actually spent.","Here's the first mistake to dodge. If you spent $450 on groceries last month, don't budget $300 and hope. Budget $450, then trim $25 next month. Small cuts stick. Big ones snap back."],tip:"Round to the nearest ten. A rough picture you finish beats a perfect one you abandon."},
{h:"Sort everything into three buckets",p:["Forget forty categories. Tracking that many turns your spending plan into a second job, and nobody keeps a second job for fun. Three buckets are all a simple budget needs.","Needs are what you must pay to live and work: rent, groceries, transport, bills, minimum debt payments. Wants make life nicer: eating out, streaming, clothes, weekends away. Future you gets savings, your emergency fund, and any extra debt payments.","A popular starting split is 50% needs, 30% wants and 20% future you. On $2,400 that's $1,200, $720 and $480. Treat it as a first guess, not a law.","Now check it against real life. Say rent is $1,000, groceries $300, transport $150, phone and utilities $150, and a loan minimum $100. That's $1,700 in needs, about 71%. Higher than 50%, and that's okay. It just tells you where to look first.","So a first draft on $2,400 might read $1,700 for needs, $400 for wants and $300 for future you. That's tight. It's also honest. Over a few months you can trim a bill or two and move $50 toward savings."]},
{h:"Pay future you first",p:["Order matters more than amounts. Most of us pay for everything, then save whatever's left. There's usually nothing left.","Flip it. The day your pay lands, move your savings out, ideally with an automatic transfer. Even $25 counts. Starting at 5% beats waiting until you can afford 20%.","Once that money has left your main account, spending the rest gets easier. The decision's already made."],tip:"Keep savings in a separate account that's a little annoying to reach. Out of sight really does help."},
{h:"Plan for the bills that ambush you",p:["This is one of the biggest budget breakers. You plan for rent, groceries and gas, then forget car registration, annual insurance, birthdays, the dentist and the vet.","None of those are surprises. They're just not monthly. Add up what they cost in a year, divide by twelve, and set that amount aside each month. That pot is called a sinking fund, which is really just a savings pot with one job.","Try it with real numbers. Car insurance $600, birthdays and gifts $300, the dentist $200, the vet $240. That's $1,340 a year, or about $112 a month. When each bill arrives, the money's already waiting."]},
{h:"Leave room to be human",p:["Here's my opinion, and I'll defend it: a budget with no fun money is a budget you'll abandon.","Give your wants bucket real money and spend it without guilt. Add a small buffer too, even $40, for the surprise gift or the cracked phone screen. Life will throw something at you. Plan for it.","Cut everything to the bone and you'll feel great for nine days. Then a bad Friday arrives, you order takeout, and the guilt does the rest. It works like a crash diet. Restriction rebounds. A plan with a little air in it lasts.","And when you blow it, which you will, don't tear the whole plan up. A rough week is information, not failure."]},
{h:"Check in once a week",p:["You don't need to log every coffee. Pick one day, maybe Sunday evening, and spend five minutes looking at each bucket. Ask two things. Am I on track for the month? What's one small change for next week?","Here's what that looks like. By day 20 your groceries bucket shows $210 spent of $300. You're ahead, so you leave it alone. Or it shows $290, so next week you cook from the freezer. No drama. Just adjustments.","One change. Not five. Changing everything at once is how people burn out and decide budgeting just isn't for them.","Expect the first month to feel clumsy. Most budgets get dropped before they've had time to fit. That weekly check is the whole upkeep of a simple budget. Adjust the numbers, not your opinion of yourself."]},
{h:"Do this tonight",p:["Open your banking app and write down your take-home pay. That's it. That's step one, and it takes about two minutes. Tomorrow, tackle the statements."]}]),
P("10-realistic-ways-to-make-money-online","10 Realistic Ways to Make Money Online","Make Money Online","2026-09-24",8,"aspect-[3/4]","bg-beige","Skip the get-rich-quick noise. These ten options are real, beginner-friendly, and need little or no upfront cost.",[
{h:"Services you already know how to do",p:["Writing, design, virtual assistance, tutoring and bookkeeping can all be sold online. Start with one skill and one small offer."]},
{h:"Selling products",p:["Digital templates, printables, and print-on-demand products let you sell without holding stock."]},
{h:"Be honest about timelines",p:["Most people earn little in the first months. Treat it as a skill you are building."],tip:"Set a 90-day experiment before judging results."}]),
P("7-side-hustles-you-can-start-with-your-phone","7 Side Hustles You Can Start With Your Phone","Side Hustles","2026-09-20",5,"aspect-[2/3]","bg-mist","You do not need a laptop to start earning. Here are seven ideas that work from your phone.",[
{h:"Ideas to try",p:["Social media management for small businesses, short-form video editing, reselling secondhand items, mobile photography, transcription, survey and testing apps, and delivery or errand services."]},
{h:"How to pick one",p:["Choose the idea that matches a skill you already have and that you can do in short, regular sessions."],tip:"Start with one hustle for 30 days before adding another."}]),
P("how-to-save-money-when-you-dont-earn-much","How to Save Money When You Don't Earn Much","Saving","2026-09-15",6,"aspect-[4/5]","bg-beige","Saving on a small income is about consistency, not big numbers. Start where you are.",[
{h:"Start tiny",p:["Saving a small fixed amount every week builds the habit. The amount can grow later."]},
{h:"Cut quietly",p:["Review subscriptions, bank fees and food waste. Small leaks add up faster than occasional big treats."]},
{h:"Build a mini emergency fund",p:["Aim for one small buffer first, then grow it toward a month of essentials."],tip:"Keep savings in a separate account so it is harder to spend."}]),
P("10-ai-tools-that-can-make-your-life-easier","10 AI Tools That Can Make Your Life Easier","AI Tools","2026-09-10",7,"aspect-[3/4]","bg-mist","From planning your week to drafting emails, these AI tools save real time when used well.",[
{h:"Where AI helps most",p:["Writing and editing, research, meal and budget planning, scheduling, note-taking and summaries, design drafts, and learning new skills."]},
{h:"Use it carefully",p:["Check facts, protect private data, and treat AI output as a first draft."],tip:"Check each tool's current pricing and privacy policy before you sign up."}]),
P("how-to-start-freelancing-as-a-beginner","How to Start Freelancing as a Beginner","Freelancing","2026-09-05",7,"aspect-[2/3]","bg-beige","Pick a skill, build three samples, and pitch your first client. Here is the simple path.",[
{h:"Choose one service",p:["Clear beats broad. Offer one service to one type of client."]},
{h:"Build a mini portfolio",p:["Create three sample projects, even unpaid or made-up ones, to show what you can do."]},
{h:"Pitch and price",p:["Send short, specific messages. Price by project when you can, and never work without clear terms."],tip:"Ask for a deposit before starting."}]),
P("simple-money-habits-that-can-improve-your-finances","Simple Money Habits That Can Improve Your Finances","Personal Finance","2026-08-30",5,"aspect-[4/5]","bg-mist","Small habits beat big plans. Seven routines that quietly improve your finances.",[
{h:"Habits worth building",p:["Check your balance weekly, automate savings, wait 48 hours before non-essential purchases, track subscriptions, and review your goals monthly."]},
{h:"Make it stick",p:["Attach each habit to something you already do, like your Sunday coffee."],tip:"Begin with one habit, not seven."}]),
P("how-students-can-build-multiple-income-streams","How Students Can Build Multiple Income Streams","Make Money Online","2026-08-25",6,"aspect-[3/4]","bg-beige","Studying leaves little time, but flexible income streams can fit around classes.",[
{h:"Flexible options",p:["Tutoring, freelance writing, campus services, selling notes or templates, and part-time remote work can all fit around a timetable."]},
{h:"Protect your studies",p:["Cap your hours and keep one simple stream simple before adding another."],tip:"Put your income into a separate account to track it."}])
];
export const getPost=(s:string)=>posts.find(p=>p.slug===s);
export const fmt=(d:string)=>new Date(d).toLocaleDateString("en-US",{year:"numeric",month:"short",day:"numeric"});
